### ISSUE TITLE
Bug:"Super Breakout" game select switch missing

### ISSUE THREAD

**Issue by CO-Windler** [mamedev/www.mamedev.org#24]
The Atari arcade game "Super Breakout" contains 3 different games that the player can select. But in MAME the game select switch seems to be missing, so it only plays "Progressive Breakout" mode.

https://strategywiki.org/wiki/Super_Breakout

**Comment by stilett0** [comment]
Two things:

1. You opened this issue against the www.mamedev.org repo, which is the website. You should have opened your issue against the "mame" repo at https://github.com/mamedev/mame ... except:

2. Except that this sort of gamer-centric issue is much better suited for the end user issue ticket tracker at https://mametesters.org . Please send such issues there in the future, The github issue tracker is better suited to developer/coder-related issues.

Closed.

**Comment by Tafoid** [comment]
For what it is worth, there is a "Machine Configuration" setting in the TAB menu which allows all 3 modes to be selected.

**Comment by stilett0** [comment]
> For what it is worth, there is a "Machine Configuration" setting in the TAB menu which allows all 3 modes to be selected.

Thanks, I didn't even check, and neither did the OP.
