### ISSUE TITLE
Bugs: "Hard Drivin"/"Race Drivin" various issues

### ISSUE THREAD

**Issue by CO-Windler** [mamedev/www.mamedev.org#25]
There are various bugs and issues related to games of the harddriv.cpp driver. (Unless mentioned otherwise, I tested them in the default cockpit versions.)

**- drift makes car skid too long**

The steering in the Atari arcade games "Hard Drivin" and "Race Drivin" in MAME behaves  odd. Once the car started to drift for a while and left the road, it often keeps spinning (even on the grass) like a carousel and becomes very hard to control for the rest of the game like driving on ice. This can only be stopped by braking the car to complete halt (0 mph). I am not sure if this is a MAME or game bug, or if this was even intentional game design, simulating excessive tyre wear or other car damage affecting steering - possibly exaggerated as a penalty for bad players.

(I control it by mouse on a slightly underpowered laptop with 1.6GHz Core2Duo and Intel graphics. The game plays well but often at about 90% speed. Setting steering wheel sensitivity "6" works best.)

Strange is that seems to happen mainly in the cockpit versions. The upright versions AFAIK don't skid forever on grass, so this seems to be a MAME bug. I suspect that the car physics DSP somehow gets out of sync with the game engine or isn't resetted properly. It feels like when it acts like a state machine that by driving faults (strong steering at too high velocity/offroad) switches into a "strong skidding" mode which is intended to be switched back to regular driving mode when the car slows down enough (possibly by resetting that chip with a special signal??) but fails. Please fix this.

**- "Street Drivin" brake pedal miswired**

In "Street Drivin" the brake pedal does nothing, which makes the Super Stunt Track impossible to finish. The test mode shows that the brake in MAME is miswired; it moves a wrong bargraph instead of "brake pedal". Please fix this.

Also the shifter can not be used, but this is likely a game bug, because in this prototype game it is nowhere mentioned in test mode and was likely not implemented.

**- controls calibration fails (test mode)**

In "Race Drivin" upright and "Street Drivin" (also "Panorama"?) the controls calibration in test mode fails with a message that the brake pedal is out of specs or such ("wait 10 minutes"), which prevents calibration of the steering wheel sensitivity.

**- gearshift behaves odd**

In cockpit versions of "Hard Drivin"/"Race Drivin" the shift lever is hard to set into neutral ("N") position through keyboard. When I shift into or out of reverse gear (needs to be enabled in test mode control settings), I have to double-clutch (push clutch and accelerate) in neutral position before I can shift to a forward gear again. When not in neutral during this, it will stay in reverse despite the dashboard displays a forward gear. Even in auto-transmission mode intermediate throttle in neutral mode is necessary to properly shift in and out of reverse gear. (I like to drive stunts and need it.) Technically the shift lever is an analogue joystick that would need more finetuning to be emulated on keyboard keys or mouse buttons. 

Also the gas and brake pedals behave odd when set as digital buttons. Brake often is stuck after MAME start (press once to release), and IMO there should be separate settings for down and up rate e.g. to release the brake faster to reduce skidding.

**- save state not working**

When in "Hard Drivin" or "Race Drivin" I save a game state, after reload the game shows a GSP board timing(?) error and resets itself. I enjoy to train stunt tricks and want to load gamestates at different spots. Please fix this.

**- car crash into invisible object**

In these games when on the "race track" the car crashes somewhere near the grey drawbridge, after the usual "instant replay" the car is dropped back onto the road (falling 1m out of the sky?) at a certain spot with the drawbridge in sight. But if I push the gas pedal (rolling about 1m in any direction) the car keeps crashing into an invisible barrier (windshield shatters), is dropped back on the very same spot and so on; crashing from there again and again until time runs out. I am not sure if this is a MAME bug or game bug or even nasty little prank played by a poorly simulated Slapstick chip.

The car also can fall through the road in various other spots when slightly offroad. E.g. on the original track when after the U-turn your car slowly drives down the talus at the right road side (a bit like a bicycle jamming its wheel in a tram rail?), it plummets down a timehole and keeps spinning and tumbling in the sky with graphics mess for about 30s(?) while gaining >30k points(!). This may be a cheat but is likely just a pug. The car finally will explode and is put back on the road.

**- graphic glitches (flowers in the sky)**

In "Race Drivin" on the "original track" driving down the trough, sometimes shows flowers floating in the sky. This does not happen in "Hard Drivin". Is this a Slapstick bug?

In "Hard Drivin" cockpit there are small rocks (milestones?) on the orange sides of the road. But in all other game variants (upright, "Race Drivin" etc.) there are none. Is this authentic game behaviour or a MAME bug? (The rock looks flat when seen from the side and seems to be the only pixel graphics sprite in the entire game, so it was likely a leftover from early graphics engine experiments with textures.)

Generally these games have many graphics glitches. Particularly polygon priority bugs also exist on the arcade machine (and home versions). But occasionally the road and other objects look "bent" when driven onto from an unexpected angle. Is this a game bug or do helper chips in MAME run out of sync (like suggested by the save state bug)?

**Comment by stilett0** [comment]
Two things:

1. You opened this issue against the www.mamedev.org repo, which is the website. You should have opened your issue against the "mame" repo at https://github.com/mamedev/mame ... except:

2. Except that this sort of gamer-centric issue is much better suited for the end user issue ticket tracker at https://mametesters.org . Please send such issues there in the future, The github issue tracker is better suited to developer/coder-related issues.

Closed.
