### ISSUE TITLE
Bug: "Marble Madness" music missing

### ISSUE THREAD

**Issue by CO-Windler** [mamedev/www.mamedev.org#26]
In the Atari arcade game "Marble Madness" in level 4 the music often stops preliminary. I.e. when the marble reaches the popup bollards (those make tooting sounds), the music often stops (only when you die?) and won't continue to the 2nd part.

**Comment by stilett0** [comment]
Two things:

1. You opened this issue against the www.mamedev.org repo, which is the website. You should have opened your issue against the "mame" repo at https://github.com/mamedev/mame ... except:

2. Except that this sort of gamer-centric issue is much better suited for the end user issue ticket tracker at https://mametesters.org . Please send such issues there in the future, The github issue tracker is better suited to developer/coder-related issues.

Closed.
