### ISSUE TITLE
Bug: replugged USB mouse not recognized

### ISSUE THREAD

**Issue by CO-Windler** [mamedev/www.mamedev.org#27]
By a bad mouse cable I discovered this odd behaviour. In Win10 (an older version) when the USB mouse is (e.g. accidentally) unplugged during game, after replugging it is not recognized anymore until MAME is completely terminated. This can get annoying when the player tries to plugin a mouse that is better suited for gaming.

Strange is that after exiting the game, the main menu will still see the mouse , but any started games (same or others) will not see the mouse until MAME is fully exitted.

**Comment by stilett0** [comment]
Two things:

1!. You opened this issue against the www.mamedev.org repo, which is the website. You should have opened your issue against the "mame" repo at https://github.com/mamedev/mame ... except:

2. Except that this sort of gamer-centric issue is much better suited for the end user issue ticket tracker at https://mametesters.org . Please send such issues there in the future, The github issue tracker is better suited to developer/coder-related issues.

[EDIT] Actually, this might be better suited to post at a forum like https://forums.bannister.org before doing 2.

Closed.
